
member:
  id: 'badge'
  parent_id: 'big_badge'
  rank: 'Semester(pledge_semester)'
  data:
    name: 'PreferredName(first_name, preferred_name, last_name)'
    affiliations: 'affiliations'

dot:

  class:
    node:
      tree:
        label: '{name}\n{affiliations}'

