[tool.poetry]
name = "snutree"
version = "0.3.0"
description = "Visualize big–little brother/sister relationships in Greek-letter organizations"
authors = ["Lucas Flowers <laf62@case.edu>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.9"
mypy = "^0.910"
pytest = "^6.2.4"
pylint = "^2.10.2"
isort = "^5.9.3"
flake8 = "^3.9.2"
pytest-cov = "^2.12.1"
yamllint = "^1.26.3"
restructuredtext-lint = "^1.3.2"
pytest-watch = "^4.2.0"
black = "^21.7b0"
networkx = "^2.6.2"
hypothesis = "^6.15.0"
autoflake = "^1.4"

[tool.poetry.dev-dependencies]

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
