[tool.poetry]
name = "snutree"
version = "0.3.0"
description = "Visualize big–little brother/sister relationships in Greek-letter organizations"
authors = ["Lucas Flowers <laf62@case.edu>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
