from collections.abc import Iterable, Iterator
from typing import Generic, Protocol, TypeVar

# pylint: disable=unused-argument

T = TypeVar("T")

class InDegreeProtocol(Protocol[T]):
    def __call__(self) -> Iterator[tuple[T, int]]: ...
    def __getitem__(self, key: T) -> int: ...

class DiGraph(Generic[T]):
    in_degree: InDegreeProtocol[T]
    def __init__(self, incoming_graph_data: "DiGraph[T]" = ...) -> None: ...
    def subgraph(self, nodes: Iterable[T]) -> "DiGraph[T]": ...
    def add_nodes_from(self, nodes_for_adding: Iterable[T]) -> None: ...
    def add_edges_from(self, ebunch_to_add: Iterable[tuple[T, T]]) -> None: ...
    @property
    def nodes(self) -> Iterable[T]: ...
    def edges(self) -> Iterable[tuple[T, T]]: ...
    def add_edge(self, u_of_edge: T, v_of_edge: T) -> None: ...
    def add_node(self, node_for_adding: T) -> None: ...
    def __contains__(self, item: T) -> bool: ...
    def __iter__(self) -> Iterator[T]: ...

def weakly_connected_components(G: DiGraph[T]) -> Iterable[set[T]]: ...
def tree_all_pairs_lowest_common_ancestor(G: DiGraph[T]) -> tuple[tuple[T, T], T]: ...
