
member:

  id: badge
  parent_id: big_badge
  rank: Semester(semester)
  classes:
    - Enum(status)
  data:
    badge: badge
    last_name: last_name
    name: PreferredName(first_name, preferred_name, last_name)

  custom:

    - id: 'reorganization'
      rank: 'Spring 1989'
      classes:
        - 'reorganization'

    - id: 'kappa_delta'
      rank: 'Spring 1982'
      classes:
        - 'chapter'
      data:
        name: 'Kappa Delta Chapter'
        college: 'Duquesne University'

tree:

  # names:
  #   root: 'root'
  #   tree: 'tree'
  #   unknown: 'unknown'
  #   rank: 'rank'

  roots:
    - reorganization
    - kappa_delta

dot:

  seed: 6584

  names:

    # TODO Update names when revision is complete
    root_graph_name: 'family_tree'
    tree_graph_name: 'members'
    ranks_left_graph_name: 'datesL'
    ranks_right_graph_name: 'datesR'
    rank_key_suffix_left: 'L'
    rank_key_suffix_right: 'R'

  custom:

    edge:

      # Connect refounders from the old chapter to Reorganization
      'reorganization,1031':
        style: dashed
      'reorganization,1034':
        style: dashed
      'reorganization,1035':
        style: dashed
      'reorganization,1036':
        style: dashed
      'reorganization,1038':
        style: dashed
      'reorganization,1039':
        style: dashed
      'reorganization,1041':
        style: dashed

  class:

    graph:

      # TODO Read booleans correctly

      root:
        size: '80'
        ratio: compress
        pad: .5, .5
        ranksep: '.15'
        nodesep: '.5'
        label: 'Family Tree: Delta Alpha Chapter of Sigma Nu Fraternity'
        labelloc: 't'
        fontsize: 110
        concentrate: 'false'

    node:

      root:
        style: filled
        shape: box
        penwidth: 2
        width: 1.63
        fontname: dejavu sans

      tree:
        fillcolor: .11 .71 1. # A goldish color

      rank:
        color: none
        fontsize: 20
        fontname: dejavu serif
        label: '{rank}'

      member:
        label: '{name}\nΔΑ {badge}'

      unknown:
        height: 0
        width: 0
        style: invis

      Candidate:
        label: '{name}\nΔΑ {badge}'

      Brother:
        label: '{last_name}\nΔΑ Brother'

      Expelled:
        label: 'Member Expelled\n{badge}'

      chapter:
        color: none
        fillcolor: none
        label: '{name}\n{college}'

      reorganization:
        height: .6
        label: 'Refounders'
        shape: oval

    edge:

      root:
        arrowhead: none

      rank:
        style: invis

      unknown:
        style: dotted
        weight: 10

